### ISSUE TITLE
About the download of “New light field image dataset (EPFL)”

### ISSUE THREAD

**Issue by Twelve918** [YingqianWang/Awesome-LF-Image-SR#1]
Excuse me, I can't download this dataset   https://www.epfl.ch/labs/mmspg/downloads/epfl-light-field-image-dataset/   .If you have downloaded it, can you share it with me, thank you very much

**Comment by YingqianWang** [comment]
Do you need the raw data (.LFR files) or the decoded data (.mat files)? If you only need the decoded light fields, you can turn to the LF-InterNet Repo (https://github.com/YingqianWang/LF-InterNet) to download the training/test datasets, where the EPFL dataset is already included.

**Comment by YingqianWang** [comment]
All scenes (LFR files) and camera calibration data of the EPFL dataset are available at https://pan.baidu.com/s/1175dV3Sj8y9K2FPYxjsuEg (Keys: NUDT)

**Comment by i328326681** [comment]
Thank you very much!



发自我的iPhone


------------------ Original ------------------
